apiVersion: apps/v1
kind: Deployment
metadata:
  name: multifactor-auth
  labels:
    app: multifactor-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multifactor-auth
  template:
    metadata:
      labels:
        app: multifactor-auth
    spec:
      containers:
      - name: multifactor-auth
        image: multifactor-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: multifactor-auth-service
spec:
  type: ClusterIP
  selector:
    app: multifactor-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
